"use client";

// import type { Metadata } from "next";
import { Buda } from "next/font/google";
import "../globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Suspense } from "react";
import Loading from "@/components/Loading";

const buda = Buda({
  weight: "300",
  subsets: [],
  variable: "--font-buda",
});

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      placeholderData: () => ({
        pages: [
          {
            data: [
              {
                id: 1,
                title: "Modern Downtown Apartment",
                price: 500000,
                location: {
                  city: {
                    name: "Downtown",
                    state: {
                      name: "California",
                    },
                  },
                  longitude: -122.419416,
                  latitude: 37.774929,
                },
                type: "Apartment",
                bedrooms: 2,
                bathrooms: 2,
                area: 1200,
                imageUrl: "/images/property-1.jpg",
                description:
                  "A beautiful modern apartment in the heart of downtown.",
              },
              {
                id: 2,
                title: "Suburban Family Home",
                price: 750000,
                location: {
                  city: {
                    name: "Suburbs",
                    state: {
                      name: "California",
                    },
                  },
                  longitude: -122.419416,
                  latitude: 37.774929,
                },
                type: "House",
                bedrooms: 4,
                bathrooms: 3,
                area: 2500,
                imageUrl: "/images/property-2.jpg",
                description: "Spacious family home with a large backyard.",
              },
              {
                id: 3,
                title: "Luxury Beach Villa",
                price: 1200000,
                location: {
                  city: {
                    name: "Beachfront",
                    state: {
                      name: "California",
                    },
                  },
                  longitude: -122.419416,
                  latitude: 37.774929,
                },
                type: "Villa",
                bedrooms: 5,
                bathrooms: 4,
                area: 3500,
                imageUrl: "/images/property-3.jpg",
                description:
                  "Stunning beachfront villa with panoramic ocean views.",
              },
            ],
            current_page: 1,
            has_more: false,
          },
        ],
        pageParams: [1],
      }),
    },
  },
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body
          className={`${buda.variable} antialiased min-h-screen flex flex-col overflow-x-hidden`}
        >
          <Navbar />
          <main className="flex-1">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
          <Footer />
        </body>
      </html>
    </QueryClientProvider>
  );
}
